name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Production
        run: |
          npm run knex_migration
          npm run prod_deploy
        env:
          DB_USER: ${{ secrets.DB_USER_STAGING }}
          DB_HOST: ${{ secrets.DB_HOST_STAGING }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_STAGING }}
          DB_PORT: ${{ secrets.DB_PORT }}
